### PR TITLE
Addition of Pretrained models for MachineLearning.Vision, Audio and Text

### LINKED ISSUE #21: MachineLearning_Toolkit: Wrong warning message when run installMachineLearningToolkit for the first time
#### Description:

I did a installation with the following steps:
 1. Install daily alpha
 2. Compile Python_toolkit from master
 3. Compile MachineLearning_toolkit from master
 4. Use InstallPythonToolkit component
 5. Use InstallMachineLearningToolkit component

During the step 5, it takes 3-4s to load the component. After loading, with nothing is connected to the run toggle (default as false), it is giving the following warning message. (PS These warning message are from the Private Fields of Invoke.cs from MachineLearning_Toolkit.)
image
1. ModuleNotFoundError : No module named 'MachineLearning_Engine'
1. ModuleNotFoundError : No module named 'numpy'

However, The warning message will not be there if we create a new InstallMachineLearning component (without running the previous InstallMachineLearning component). But if we closed Rhino and reopen Grasshopper, it will happen again. So the warning message is only happening when the first time InstallMachineLearning is loaded, and only happen once. 

This seems to me going to the opposite side we want the warning message - it should not warn the the first time because it is of course not there before installation. And thinking about it, it seems unnecessary to have a checking for InstallMachineLearning component.

### LINKED ISSUE #22: MachineLearning_Toolkit: Checking if python toolkit and machinelearning toolkit is installed for InstallMachineLearning component
#### Description:

As title, a feature to check if the python toolkit and machinelearning toolkit are installed successfully is needed for the InstallMachineLearning component. We may considering calling InstallPythonToolkit if checking is failed. 

This feature is also related to #21

### LINKED ISSUE #29: Use a requirements.txt file to install the necessary packages
#### Broken rules:

Packages to be installed are now hardcoded into the toolkit and not very clear what they are.

#### Suggestions to restore compliance:

Use a requirements.txt file as common practice for pip.

### LINKED ISSUE #33: Improve the feedback when a package is missing
#### Description:

If there is an `ImportError` or some other error that causes a crash in the import, the message is not clear.

### LINKED ISSUE #39: Automatically install python before installing the machinelearning toolkit

### LINKED ISSUE #44: Namespaces should be restricted to BH.*.MachineLearning
#### Broken rules:

There are currently some methods within a `Vision` namespace.

#### Suggestions to restore compliance:

To clarify to the user when he/she is going into python land, it would be good to restrict the namespaces to only `MachineLearning`.

### LINKED ISSUE #49: Wrap pretrained models for common tasks in different fields
#### Description:

- [x] Vision
- [ ] Text
- [ ] Audio 
- [ ] Geometry

### PR DESCRIPTION
**Pull request by epignatelli**
Depends on https://github.com/BHoM/Python_Toolkit/pull/41

### Issues addressed by this PR

Closes #49 
Closes https://github.com/BHoM/Python_Toolkit/issues/29
Closes https://github.com/BHoM/Python_Toolkit/issues/33
Closes #44 
Closes #39 
Closes #22 
Closes #21

This pull request:
- Introduces new capabilities for computer vision using pretrained models.
- Restructures the namespaces to align to https://github.com/BHoM/MachineLearning_Toolkit/issues/44 and be more systematic
- Provides an example on how to wrap existing models around a bhom method

Namespaces implemented:
- [x] Vision
- [x] Audio
- [x] Text
- [ ] Geometry

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Em3z-6G9WRxPgzuztBkSEbgBHUhIVwl1LgKzjwgB68v-fQ?e=hrG5hW

### CODE REVIEW

**Comment by epignatelli** [comment]
Alright, I think this is ready for review now. 

I haven't been able to find pretrained models that solve interesting tasks for geometry, but only models that needs training (data is provided, though).

I would start reviewing from this point to set the ball rolling.

**Comment by al-fisher** [comment]
Just putting a `do-not-merge` on until feature freeze on the installer is over next week.
@epignatelli 
Testing can continue straight away though as you say 😄 - so we are ready to merge in 4.0 alphas!

**Comment by al-fisher** [comment]
Thanks @epignatelli - those fixes seemed to solve the install issue.
Components in test files however still failing for me - but with new error:
image

**Comment by al-fisher** [comment]
`BH.Engine.MachineLearning.Vision.Compute.DetectObjects` & `RecogniseObject` are giving results for me now 🐕 🌭 

image

current_plot

current_plot2

File: MachineLearning_Engine/Query/Import.cs [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+            if (moduleInstalled)
+                return Python.Query.Import(module);
+
+            // if module is not installed ask for automatic installation
+            string installMessage = $"Cannot import module {module}, because the MachineLearning_Toolkit is not installed. Do you want to install the module?";
+            DialogResult confirmResult = MessageBox.Show(installMessage, "BHoM package manager", MessageBoxButtons.YesNoCancel);
+
+            if (confirmResult == DialogResult.Yes)
+            {
+                if (!Python.Query.IsModuleInstalled("MachineLearning_Engine"))
```
Comment (BingWangUS) [inline MachineLearning_Engine/Query/Import.cs:48]: I found a typo here that is stopping the auto-installation running. It should be MachineLearning-Engine, instead of MachineLearning_Engine, because it is checking the MachineLearning-Engine.egg-link file.

File: MachineLearning_Engine/Query/Import.cs [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+                }
+                if (!Python.Query.IsModuleInstalled("MachineLearning_Engine"))
+                {
+                    Reflection.Compute.RecordWarning($"{module} has been installed, please restart the UI");
+                    Application.Restart();
+                }
+            }
+            else
+            {
+                string errorMessage = $"Cannot import module {module} because no valid version of Python for the BHoM has been found.\n" +
```
Comment (BingWangUS) [inline MachineLearning_Engine/Query/Import.cs:56]: Typo here and below: should be machine learning toolkit instead of python toolkit.

**Review by BingWangUS — COMMENTED** [review]
I did not review the PR completely as it is a big refactor. 

Only tested the auto-installation part and it works as expected.

BTW this PR seems to me also closing #44, #39, #22, #21. @epignatelli can you confirm?

**Comment by epignatelli** [comment]
Thank you @BingWangUS ! Comment addressed and yes, this also fixes all the issues you mentioned.

**Comment by al-fisher** [comment]
Will be good to review and merge this PR now. @BingWangUS have seen you have tested some aspects. Are you able to run/cover some of the sample files. @MarthaVoul how about you?
I can confirm the Vision methods `SegmentImage`, `RecogniseObject`, `DetectObject` are all working.
Also the Text `SentimentAnalysis`

Audio are not working for me - getting the following error on `SynthesiseSpeech` : 

```
1. This component failed to run properly.
- Error: RuntimeError : Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
- Occured in  BH.Engine.Python.Compute.Invoke(PyObject module, String method, IEnumerable`1 args, Dictionary`2 kwargs)
     called from BH.Engine.MachineLearning.Base.Compute.Invoke(String method, Object[] args)
- Are you sure you have the correct type of inputs? Check their description for more details.

```

Also the `FindContours` on `SegmentImage` `Tensor` output is returning error:

```
1. This component failed to run properly.
- Error: Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Collections.Generic.List`1[System.Collections.Generic.List`1[System.Double]]'.
- Occured in  BH.UI.Base.Caller.Run(List`1 inputs)
     called from BH.UI.Base.Caller.Run()
- Are you sure you have the correct type of inputs? Check their description for more details.
```

@epignatelli can grab a minute to catch up on these tomorrow.
Big PR and now beta released - keen to get to a point to merge - even if raise some specific separate issues

File: MachineLearning_Engine/Compute/__init__.py [hunk 3]
```diff
@@ -19,13 +19,33 @@
...
-from . import MinMaxScaler 
-from . import StandardScaler
-from . import PolynomialFeatures
-from .ClimateCharts import Diurnal
-from .ClimateCharts import UTCI
-from .ClimateCharts import Frequency
-from .ClimateCharts import Heatmap
\ No newline at end of file
+
+from . import LinearRegression
```
Comment (BingWangUS) [inline MachineLearning_Engine/Compute/__init__.py]: This line need to be removed.

**Review by BingWangUS — DISMISSED** [review]
Did 3 tests - installation, Structured.Examples and LogisticRegression.Examples. Focus on functionality only.

A. Installation:
1) Install latest alpha 09/30
2) Remove Extensions\Python folder
3) Compile latest Python PR and this PR.
4) Open Rhino 5, Open the test script 15 [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/MachineLearning_Toolkit/MachineLearning%2315-ScoreMethod?csf=1&web=1&e=j9c2PZ).
5) A warning pop up, asking for installation.
6) Select yes, wait, recompute grasshopper. It is failing because there is an import error. See my comment on code. Removing the line then it will work fine.

B. Structured.Examples
Works fine after removing the import line.

C. LogisticRegression.Examples
Works fine after removing the import line.

Another thought is that we will need some description but this could be a future issue.

**Comment by BingWangUS** [comment]
Can we have an example for Support Vector Regression? After reading an example [here ](https://scikit-learn.org/stable/auto_examples/svm/plot_svm_regression.html#sphx-glr-auto-examples-svm-plot-svm-regression-py), I wonder if we need to have an optional input for the variables because they are playing an important role in this model and default may not always work. A string input like "C=100, gamma=0.1, epsilon=.1" will be helpful.

File: MachineLearning_Engine/Compute/Text/Answer.cs [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+{
+    public static partial class Compute
+    {
+        /*************************************/
+        /**** Public Methods              ****/
+        /*************************************/
+
+        public static string Answer(string question, string context = "", bool gpu = false)
+        {
+            return BH.Engine.MachineLearning.Base.Compute.Invoke("Answer.infer", question, question, gpu).As<string>();
```
Comment (BingWangUS) [inline MachineLearning_Engine/Compute/Text/Answer.cs]: Wonder if the second "question" is a typo?

File: MachineLearning_Engine/Compute/Text/Answer.py [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+# GNU Lesser General Public License for more details.
+#
+# You should have received a copy of the GNU Lesser General Public License
+# along with this code. If not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.
+#
+
+from transformers import pipeline
+
+
+def infer(question: str, context: str,		gpu: bool):
```
Comment (BingWangUS) [inline MachineLearning_Engine/Compute/Text/Answer.py]: Here looks like a typo too.

**Comment by BingWangUS** [comment]
> Can we have an example for Support Vector Regression? After reading an example [here ](https://scikit-learn.org/stable/auto_examples/svm/plot_svm_regression.html#sphx-glr-auto-examples-svm-plot-svm-regression-py), I wonder if we need to have an optional input for the variables because they are playing an important role in this model and default may not always work. A string input like "C=100, gamma=0.1, epsilon=.1" will be helpful.

I prototyped an optional argument input for SVR model (https://github.com/BHoM/MachineLearning_Toolkit/tree/MachineLearning%2352-PrototypeArguments), which could be a nice additional feature for all structured models. We can take care of this later.

**Review by BingWangUS — COMMENTED** [review]
Redo the 3 tests - installation, StructedExample, LogisticExample. All works as expected. Thank you @epignatelli!

**Comment by epignatelli** [comment]
Thanks @BingWangUS !
I hav ejust pushed all the fixes - everything should work ok now.

Require testing:
- Audio.SpeechSynthesis
- ~Text.Summarisation~
- Text.Answering

**Comment by BingWangUS** [comment]
1. Tested Text.Summarisation, works fine. Added the test script into the example folder.

2. Tested Text.Answer, failed. It open a new Rhino 5 window with the following error message.
image

3. Tested Audio.SynthesisSpeech, failed. Added the test script into the example folder.
Error message as below if gpu option is false: RuntimeError : Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Error message as below if gpu option is true: AttributeError : module 'torch.cuda' has no attribute 'is_avaliable'

4. Audio.Example script has the same issue as above. (the audioTensor BHoM object in the script seems missing internalised data) 

5. Vision.Example script works for most methods (Yes it find all kinds of lovely dogs!). 
Only the FindContours giving the following errors: Error: Unable to cast object of type 'System.Collections.Generic.List`1[System.Object]' to type 'System.Collections.Generic.List`1[System.Collections.Generic.List`1[System.Double]]'.

image
image
image

File: MachineLearning_Engine/Compute/Vision/RecogniseObject.cs [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+    public static partial class Compute
+    {
+        /*************************************/
+        /**** Public Methods              ****/
+        /*************************************/
+
+        [Description("Returns the type of object in the image, e.g. an apple")]
+        [Input("Image path", "The absolute path to the image to analyse")]
+        [Input("Gpu", "If true, computation is accelarated using a capable gpu")]
+        [Output("Object", "The probabilities (score) for each class. Use the Query.ImageClasses() method to match ")]
```
Comment (BingWangUS) [inline MachineLearning_Engine/Compute/Vision/RecogniseObject.cs:37]: Question here: Is this returning probabilities or object name? And the amount of output seems different from the objects in the image, is it trying to use one type for the group?

**Comment by epignatelli** [comment]
Thanks @al-fisher @BingWangUS for the tests and the help!

I raised two issues on what is currently not working properly, you can find them at:
https://github.com/BHoM/MachineLearning_Toolkit/issues/52 and https://github.com/BHoM/MachineLearning_Toolkit/issues/53.

@al-fisher I think I am ok for this to be merged with that feedback if the toolkit is okay from your side!

**Review by al-fisher — APPROVED** [review]
Given the newly raised issues and based on the samples I have tested (and just re-tested).
Happy for this to be merged @epignatelli 
Thanks 🙏 😄 

@BingWangUS are you happy too? We can pick up further comments and issues in new and focused PRs.

**Comment by FraserGreenroyd** [comment]
Can we get a slightly better PR title before merge please :smile:

**Comment by BingWangUS** [comment]
> Given the newly raised issues and based on the samples I have tested (and just re-tested).
> Happy for this to be merged @epignatelli
> Thanks 🙏 😄
> 
> @BingWangUS are you happy too? We can pick up further comments and issues in new and focused PRs.

I'm more than happy to merge this in. I will put my comments into dedicated issues for future development.

**Comment by al-fisher** [comment]
Thanks @BingWangUS
