### PR TITLE
The toolkit autonomously build into ProgramData

### LINKED ISSUE #18: Install in ProgramData instead of AppData/Roaming
#### Broken rules:

Toolkit now installs in AppData

#### Suggestions to restore compliance:

It should be aligned with the rest of the BHoM and install in ProgramData

### PR DESCRIPTION
**Pull request by epignatelli**
### Issues addressed by this PR

Closes #18 

We now compile the toolkit into `ProgramData` as per compliance.
I added the new postbuild events, together with additional ones to copy the python files over as well.

We are now copying the python source code of the MachineLearning_Engine into `C:\\ProgramData\\BHoM\\python-3.7.3-embed-amd64\\src`, and use those to install the engine. 
The files are update at each build by the postbuild events.

If we successfully merge this, the toolkit is ready to be included in the installer.

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EmYIW2WfjUtPkIYccZ-8V8gBZTOmUfLfgK1gllazCEilcQ?e=dprvsm

### Changelog

- Removed the MachineLearning_PostBuild project for compliance
- Add new compliant PostBuild events
- Fix the installation of the ML libraries
- Build into `ProgramData`

### CODE REVIEW

**Comment by BingWangUS** [comment]
Having trouble in opening previous script. Error message from component is:

1. This component failed to run properly.
- Error: Unable to load DLL 'python37': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
- Occured in  BH.Engine.MachineLearning.Compute.InvokeNumpy(String method, IEnumerable`1 args, Dictionary`2 kwargs)     called from BH.Engine.MachineLearning.Convert.ToNumpyArray(Object collection, Type dtype)
- Are you sure you have the correct type of inputs? Check their description for more details.

Seems like we need to update dll name.

**Comment by epignatelli** [comment]
Thanks @BingWangUS !
Could I ask you to paste here the list of dlls you have in the `Assemblies` folder, please?

You can open a cmd, `cd` to the folder and `dir > list.txt`, it will save it there.

File: MachineLearning_Engine/Compute/InstallToolkit.cs [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+
+namespace BH.Engine.MachineLearning
+{
+    public static partial class Compute
+    {
+        /*************************************/
+        /**** Public Methods              ****/
+        /*************************************/
+
+        public static Output<bool, List<string>> InstallToolkit(bool force = false, bool run = false)
```
Comment (FraserGreenroyd) [inline MachineLearning_Engine/Compute/InstallToolkit.cs]: Same concern here as with Python Toolkit, perhaps we can discuss and agree there though cause it'll trickle into here?

However, on the other method, we did `run` first and `force` as the second input, could we make sure we're aligned between the 2 to not confuse people?

File: MachineLearning_Engine/Compute/InstallToolkit.cs [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+        {
+            if (!run)
+                return null;
+
+            string module;
+            List<string> installed = new List<string>();
+
+            // install pillow
+            module = "pillow";
```
Comment (FraserGreenroyd) [inline MachineLearning_Engine/Compute/InstallToolkit.cs]: Why can't we do `string module = "pillow";` given the logic here does not suggest the string could end up as anything else between these lines.

File: MachineLearning_Engine/Compute/InstallToolkit.cs [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+            Console.WriteLine($"Installing {module}...");
+            Engine.Python.Compute.PipInstall(module, force: force);
+            if (Python.Query.IsModuleInstalled(module))
+                installed.Add(module);
+
+            // install pymongo
+                module = "pymongo";
```
Comment (FraserGreenroyd) [inline MachineLearning_Engine/Compute/InstallToolkit.cs]: Wrong indentation

File: MachineLearning_Engine/Compute/InstallToolkit.cs [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+        /**** Public Methods              ****/
+        /*************************************/
+
+        public static Output<bool, List<string>> InstallToolkit(bool force = false, bool run = false)
+        {
+            if (!run)
+                return null;
+
+            string module;
+            List<string> installed = new List<string>();
```
Comment (FraserGreenroyd) [inline MachineLearning_Engine/Compute/InstallToolkit.cs]: On the Python Toolkit graphs branch @tg359 and I were working on we refactored this, to have the list of modules needing to be installed at the top, instantiated with the modules, then using a `foreach` loop to loop over each module and install it.
The joy of that is when we want to add another package we only need to update the initial list, without needing to copy/paste the install code for each new package.
What are your thoughts on that one @epignatelli ?

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

File: MachineLearning_Engine/Compute/InstallToolkit.cs (hunk 4 above)
Comment (epignatelli) [reply MachineLearning_Engine/Compute/InstallToolkit.cs]: Yeah, I had seen that, and I agree, the code is awful. 
The reason I didn't do it is that some packages have additional parameters in the `pip install`, such as version, or links.

I could group together the ones that are simple pip install and manually add the rest?

Comment (FraserGreenroyd) [reply MachineLearning_Engine/Compute/InstallToolkit.cs]: Ah ok, I hadn't considered that. I am not against doing it this way, makes it very clear what people need to do if it's the same for each module, so would be happy with this given your comment and not make any changes, it's lengthy code, but it's transparent code

Comment (epignatelli) [reply MachineLearning_Engine/Compute/InstallToolkit.cs]: ehm, sorry, :D

**Comment by BingWangUS** [comment]
> Thanks @BingWangUS !
> Could I ask you to paste here the list of dlls you have in the `Assemblies` folder, please?
> 
> You can open a cmd, `cd` to the folder and `dir > list.txt`, it will save it there.

Here you are. This is after today's alpha and rebuild python from PR 23 and machinelearning from PR 19
[dlllist.txt](https://github.com/BHoM/MachineLearning_Toolkit/files/4869816/dlllist.txt)

**Comment by epignatelli** [comment]
Ah, right, thanks. And with this configuration it does still throw that error?

**Comment by BingWangUS** [comment]
> Ah, right, thanks. And with this configuration it does still throw that error?

Yes. Tried searching python37 in both Python_Toolkit and MachineLearning_Toolkit but did not find anything. Thinking maybe a environment path issue? Where python37 is install now? FYI I do have another version of python installed.

**Comment by epignatelli** [comment]
This is quite weird, I have tried to replicate that, but it works fine for me.
What I did is:
- Download the latest [Alpha installer](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2FInstallers%2FDaily%20Alphas&FolderCTID=0x012000181C071E8B6D1E438B59C87DA36B9302)  
-  Checkout the branch of this PR for the MachineLearning_Toolki
- Compile the MachineLearning_Toolki
- Start Grasshopper and run a python command

Am I missing something?

The `python37` issue happens because `python.exe` cannot be found.
And yes, maybe that's because the python home is not added to the path (which explains why I don't have the issue).

**Comment by BingWangUS** [comment]
> This is quite weird, I have tried to replicate that, but it works fine for me.
> What I did is:
> 
> * Download the latest [Alpha installer](https://burohappold.sharepoint.com/sites/BHoM/Installers/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2FInstallers%2FDaily%20Alphas&FolderCTID=0x012000181C071E8B6D1E438B59C87DA36B9302)
> * Checkout the branch of this PR for the MachineLearning_Toolki
> * Compile the MachineLearning_Toolki
> * Start Grasshopper and run a python command
> 
> Am I missing something?
> 
> The `python37` issue happens because `python.exe` cannot be found.
> And yes, maybe that's because the python home is not added to the path (which explains why I don't have the issue).

Further down this route, I have the following python versions in my %AppData%. Python37 was last modified at May. Since I never used Python37 this is rare to me.
image

Also have the following PATH environment variable
image

But my BHoM folder python is empty.
image

Just guessing, when we install python in Python_Toolkit, maybe it found python37 already installed so then it skip the installation without any warning.

**Comment by epignatelli** [comment]
Let's take this in to the ML call, shall we?

**Comment by epignatelli** [comment]
Alright, I think I fixed the issue, guys.
Would you mind giving it another go?

**Comment by epignatelli** [comment]
Hi @BingWangUS !

So, before trying to run any python component, did you run the `InstallPythonToolkit` component?

**Comment by BingWangUS** [comment]
> Hi @BingWangUS !
> 
> So, before trying to run any python component, did you run the `InstallPythonToolkit` component?

Tried this, got this error message:
1. This component failed to run properly.
- Error: Could not find a part of the path 'C:\Users\bwang\AppData\Roaming\BHoM\python-3.7.3-embed-amd64\startup.py'.
- Occured in  BH.Engine.Python.Compute.Install(Boolean force)
     called from BH.Engine.Python.Compute.InstallPythonToolkit(Boolean run, Boolean force)
- Are you sure you have the correct type of inputs? Check their description for more details.

It is looking for AppData but not ProgramData

**Comment by FraserGreenroyd** [comment]
> It is looking for AppData but not ProgramData

Your system environment path needs deleting from AppData so it can look in ProgramData. This is a manual step of this process of gearing Python and ML toolkits for the installer from those of us that were previously building from source.

**Comment by BingWangUS** [comment]
> > It is looking for AppData but not ProgramData
> 
> Your system environment path needs deleting from AppData so it can look in ProgramData. This is a manual step of this process of gearing Python and ML toolkits for the installer from those of us that were previously building from source.

Gotcha. Found this yesterday but leaving it in case we want to do some testing. Make sense to do it manually only for user who have previous version.

Following on this, there is a PYTHONSTARTUP variable pointing to 'C:\Users\bwang\AppData\Roaming\BHoM\python-3.7.3-embed-amd64\startup.py', should it be removed as well?

**Comment by FraserGreenroyd** [comment]
> Following on this, there is a PYTHONSTARTUP variable pointing to 'C:\Users\bwang\AppData\Roaming\BHoM\python-3.7.3-embed-amd64\startup.py', should it be removed as well?

Yup, and rerun `InstallPythonToolkit` - I usually put `run` and `force` to true for the first one to make double sure :smile:

**Comment by BingWangUS** [comment]
> > Following on this, there is a PYTHONSTARTUP variable pointing to 'C:\Users\bwang\AppData\Roaming\BHoM\python-3.7.3-embed-amd64\startup.py', should it be removed as well?
> 
> Yup, and rerun `InstallPythonToolkit` - I usually put `run` and `force` to true for the first one to make double sure 😄

Okay now python is installed.

After that, I compiled ML_toolkit, open a new GH file and try to run the installMachineLearning component. Got the following:
1. This component failed to run properly.
- Error: ModuleNotFoundError : No module named 'MachineLearning_Engine'
- Occured in  BH.Engine.MachineLearning.Compute.InstallMachineLearningToolkit(Boolean run, Boolean force)
     called from BH.UI.Templates.MethodCaller.Run(Object[] inputs)
- Are you sure you have the correct type of inputs? Check their description for more details.

**Comment by epignatelli** [comment]
OK, let's take this in steps, and focus on the issue.

@BingWangUS Are you on this python branch https://github.com/BHoM/Python_Toolkit/pull/23?

**Comment by BingWangUS** [comment]
After testing, the installMachineLearning component is working.

Noting some thoughts here for reference:
1. Placing the installMachineLearningToolkit component on GH canvas takes 7s. This is not common. Not sure what is going on in the background.
2. The component will leave a note saying "ML_Engine not found" right after placing the component. Assume this is still WIP.
3. We may want to check if python toolkit is installed for this component, or run installPython in the background. Already discussed this with @epignatelli and he think this is a bigger issue that need to be handle later.

**Comment by epignatelli** [comment]
Alright guys, I am confident that all is okay now, using the correspondent Python_Toolkit pr https://github.com/BHoM/Python_Toolkit/pull/25.

@tg359 @BingWangUS can you give it a last go to this? All the previous issues should disappear now.

Before testing, just make sure you remove any occurrence of `PYTHONPATH`, `PYTHONHOME` and any python reference in the `PATH` that has to do with the BHoM Python. Those are not neded anymore :)

File: MachineLearning_Engine/Compute/InstallMachineLearningToolkit.cs [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+
+namespace BH.Engine.MachineLearning
+{
+    public static partial class Compute
+    {
+        /*************************************/
+        /**** Public Methods              ****/
+        /*************************************/
+
+        public static Output<bool, List<string>> InstallMachineLearningToolkit(bool run = false, bool force = false)
```
Comment (FraserGreenroyd) [inline MachineLearning_Engine/Compute/InstallMachineLearningToolkit.cs:44]: I'm being a PITA here, but could we get a description + input/output attributes for this? Just to help people? Also could the description give a warning that it may take time to complete (similar to the Python one)?

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
This works great, literally just a documentation request and then I'm happy to see this merged! :smile:

**Comment by epignatelli** [comment]
I am not sure what happened, but it seems like I closed this pr with a cross-repo keyword usage. Reopening now.

File: MachineLearning_Engine/Compute/InstallMachineLearningToolkit.cs (hunk 5 above)
Comment (epignatelli) [reply MachineLearning_Engine/Compute/InstallMachineLearningToolkit.cs:44]: I had to do it: https://en.wikipedia.org/wiki/Pita

File: MachineLearning_Engine/Compute/InstallMachineLearningToolkit.cs [hunk 6]
```diff
@@ -0,0 +1,94 @@
...
+    {
+        /*************************************/
+        /**** Public Methods              ****/
+        /*************************************/
+
+        [Description("Install the python bindings of the Machine Learning Toolkit. This includes standard machine learning packages \n" +
+            "as the BHoM methods developed in python. Note that this depends on the Python_Toolkit.")]
+        [Input("run", "Starts the installation of the toolkit if true. Stays idle otherwise.")]
+        [Input("force", "If the toolkit is already installed it forces a reinstall of all the packages. It does not force a reinstall of Python.")]
+        [Output("True if installation is successful, false otherwise.")]
```
Comment (FraserGreenroyd) [inline MachineLearning_Engine/Compute/InstallMachineLearningToolkit.cs]: You're using a MultiOutput - should this not be the same as the InstallPythonToolkit output attributes?

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

File: MachineLearning_Engine/Compute/InstallMachineLearningToolkit.cs (hunk 6 above)
Comment (epignatelli) [reply MachineLearning_Engine/Compute/InstallMachineLearningToolkit.cs]: Yes :D

**Review by FraserGreenroyd — APPROVED** [review]
Alright, I think that's good enough :wink:

Seriously though, nice work @epignatelli This is great!!
