### PR TITLE
Fix Query.Error and ToList

### LINKED ISSUE #65: Issue with MachineLearning.Query.Error
#### Description:
The error component which computes the R^2 value does not appear to work.

#### Screenshot of Error

image

@BingWangUS

### LINKED ISSUE #79: MachineLearning_Toolkit: Tensor ToList fails when python is returning a number instead of a list
#### Description:

This behaviour is noted in #11 but was not recognized as a bug. 
In some case, for example, using the error(score) method to calculate R2, the python part is returning the result as a single number instead of a list. When this happens, it is still recognized as a Tensor but then the Tensor ToList function will fail.

#### Steps to reproduce:

See the test script and screenshot below
[MachineLearning#9-LinearRegressionOutputs_Debug.zip](https://github.com/BHoM/MachineLearning_Toolkit/files/5816175/MachineLearning.9-LinearRegressionOutputs_Debug.zip)

image

#### Expected behaviour:

ToList should be able to distinguish the data type and cover correctly.

### LINKED ISSUE #81: MachineLearning_Toolkit: ToList method convert the data wrong when the data is not double type
#### Description:

Currently the ToList method only works for tensor with data type as double, it will fail when the data type is not double but it does not give any warning.
For example, we will need to be able convert Int for LogisticRegression.

#### Steps to reproduce:

See the test script (Logistic regression part)
[MachineLearning#65-Scores.zip](https://github.com/BHoM/MachineLearning_Toolkit/files/5823702/MachineLearning.65-Scores.zip)

image

### PR DESCRIPTION
**Pull request by BingWangUS**
### Issues addressed by this PR

Closes #65 
Closes #79 
Closes #81 

### Test files

[MachineLearning#65-Scores-allModels.zip](https://github.com/BHoM/MachineLearning_Toolkit/files/5823695/MachineLearning.65-Scores.zip)

### Changelog

 - Move Error and Coefficients methods from Query to Structured.Compute, as they only works for models under Structured. (this fix 65)
 - Rename Error method to Score method, to avoid the negative term. (include versioning)
 - Modify Score method to work with interface oM, to avoid adding method for each model.
 - Modify Coefficients method to work with interface, to avoid adding method for each model.
 - Split oM interface
 - Fix ToList method to work with different types of Tensor (fix 79 and 81)

### CODE REVIEW

**Comment by BingWangUS** [comment]
@BHoMBot check documentation compliance

**Comment by BingWangUS** [comment]
@BHoMBot check documentation compliance

**Comment by BingWangUS** [comment]
@BHoMBot check documentation compliance

**Comment by BingWangUS** [comment]
@BHoMBot check documentation compliance

**Review by KentonPhillips-BH — COMMENTED** [review]
Tested script functionality in grasshopper. Confirm R^2 score is correct by comparing to manual calculation. 
Will leave code review approval to Al / Fraser.

image

File: MachineLearning_Engine/Compute/Structured/Coefficients.cs [hunk 1]
```diff
@@ -29,18 +29,18 @@
 using System.Collections.Generic;
 using System.ComponentModel;
 
-namespace BH.Engine.MachineLearning
+namespace BH.Engine.MachineLearning.Structured
```
Comment (FraserGreenroyd) [inline MachineLearning_Engine/Compute/Structured/Coefficients.cs:32]: This will need versioning with a `Versioning_41.json` file.

File: MachineLearning_Engine/Convert/ToList.cs [hunk 2]
```diff
@@ -34,20 +36,30 @@ public static partial class Convert
         /**** Public Methods                            ****/
         /***************************************************/
 
+        [Description("Convert a Tensor to a list of data.")]
```
Comment (FraserGreenroyd) [inline MachineLearning_Engine/Convert/ToList.cs:39]: A list of what type of data? Will it always be double by default or could we later convert to a list of string? If always double then don't worry about changing.

File: MachineLearning_oM/IRegressionModel.cs [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                 
+ * GNU Lesser General Public License for more details.                          
+ *                                                                            
+ * You should have received a copy of the GNU Lesser General Public License     
+ * along with this code. If not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.      
+ */
+
+namespace BH.oM.MachineLearning
+{
+    public interface IRegressionModel { }
```
Comment (FraserGreenroyd) [inline MachineLearning_oM/IRegressionModel.cs]:
```suggestion
    public interface IRegressionModel
    {
    }
```

File: MachineLearning_oM/IScaler.cs [hunk 4]
```diff
@@ -22,6 +22,6 @@
 
 namespace BH.oM.MachineLearning
 {
-    public interface IModel { }
+    public interface IScaler { }
```
Comment (FraserGreenroyd) [inline MachineLearning_oM/IScaler.cs]:
```suggestion
    public interface IScaler
    {
    }
```

File: MachineLearning_oM/ITransformer.cs [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                 
+ * GNU Lesser General Public License for more details.                          
+ *                                                                            
+ * You should have received a copy of the GNU Lesser General Public License     
+ * along with this code. If not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.      
+ */
+
+namespace BH.oM.MachineLearning
+{
+    public interface ITransformer { }
```
Comment (FraserGreenroyd) [inline MachineLearning_oM/ITransformer.cs]:
```suggestion
    public interface ITransformer
    {
    }
```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Minor formatting changes, versioning is the key one for the namespace change (use of `PreviousVersion` looks good though). Otherwise happy to take @KentonPhillips-BH review for merging following those changes :smile:

Oh, PR title also needs improving please @BingWangUS 😉

File: MachineLearning_Engine/Compute/Structured/Coefficients.cs (hunk 1 above)
Comment (BingWangUS) [reply MachineLearning_Engine/Compute/Structured/Coefficients.cs:32]: Would a PreviousVersion work? Or it should be a versioning json for type?

File: MachineLearning_Engine/Convert/ToList.cs (hunk 2 above)
Comment (BingWangUS) [reply MachineLearning_Engine/Convert/ToList.cs:39]: To be honest I'm not sure. Currently this method is only capable to handle double as Eduardo noted and will only be used for regression methods which always return double. He did put a TODO here to handle other types but I'm not sure where the functionality will be used.

File: MachineLearning_Engine/Compute/Structured/Coefficients.cs (hunk 1 above)
Comment (FraserGreenroyd) [reply MachineLearning_Engine/Compute/Structured/Coefficients.cs:32]: Alas not as you've changed the namespace for a specific part, the only way a previous version would work is if you use one on all methods that have no changed namespace. Have you changed the namespace for all bits or just a few methods?

File: MachineLearning_Engine/Convert/ToList.cs (hunk 2 above)
Comment (FraserGreenroyd) [reply MachineLearning_Engine/Convert/ToList.cs:39]: Ok fair enough, let's leave as is then :smile:

File: MachineLearning_Engine/Compute/Structured/Coefficients.cs (hunk 1 above)
Comment (BingWangUS) [reply MachineLearning_Engine/Compute/Structured/Coefficients.cs:32]: Both namespaces exists just moved from one to the other. Should be just a previous version.

Comment (FraserGreenroyd) [reply MachineLearning_Engine/Compute/Structured/Coefficients.cs:32]: Ok, let's try that, should be ok :smile:

**Comment by BingWangUS** [comment]
@KentonPhillips-BH after following Fraser's comment, I took the chance to enhance coefficient method and it should work with all regression models now. Could you please re-test the updated test script to make sure it works as expected. Thanks.

**Comment by BingWangUS** [comment]
@FraserGreenroyd Your comment on ToList data type method points to a new bug. I give it a try to fix it but the solution now is not scalable to me. I can use some help here. Please take a look at the ToList method and let me know if you have any comment.

**Review by KentonPhillips-BH — COMMENTED** [review]
Test script works for 3 types of models; linear, SVR, and logistic

**Review by FraserGreenroyd — APPROVED** [review]
I agree @BingWangUS we might want to revisit this in the future, but for now this is working, and I don't think we have a lot of resource to improve it at this stage, so I'm happy to merge this as a working bug fix following @KentonPhillips-BH review, and we can potentially refactor in the future if you're happy with that?

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Comment by BingWangUS** [comment]
> I agree @BingWangUS we might want to revisit this in the future, but for now this is working, and I don't think we have a lot of resource to improve it at this stage, so I'm happy to merge this as a working bug fix following @KentonPhillips-BH review, and we can potentially refactor in the future if you're happy with that?

Agree. Creating new issue #82 to capture this.
